### ISSUE TITLE
Fitness Machine Service Branch Needs Testing

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#100]
@kadaan , please test this latest binary from the Fitness Machine Service Branch

It might work (might not 😂) with your IC4. 

It won't work with the fitness machine service in general however because I haven't incorporated reading the bitflags yet. (It's hardcoded to the fields that are supposed to work for the IC4 (Watts and Cadence).

You might need to enable the double power option.   

[firmware.zip](https://github.com/doudar/SmartSpin2k/files/6013810/firmware.zip)

**Comment by kadaan** [comment]
@doudar Interestingly I get this page when connecting to the device after flashing the firmware.  Is the SPIFFS missing int he firmware you uploaded?

![image](https://user-images.githubusercontent.com/1904898/108584587-6613e300-72f7-11eb-8798-9c72e9583468.png)

**Comment by kadaan** [comment]
@doudar. I was able to work around this by uploading the filesystem image from PlatformIO

**Comment by doudar** [comment]
@kadaan  Any updates from the testing session last night after the bit field implementation?

**Comment by kadaan** [comment]
FTMS decoding is in this branch and a big refactoring to abstract away different sensor data providers.

**Comment by doudar** [comment]
Merged into develop-release-candidate
