### ISSUE TITLE
[BUG] Debugging output without FTMS device connected shows SensorData(Null):[ ]

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#108]
### Description

With a normal CPS BLE sensor connected, debug shows output like:

23 0 7e 0 0 a4 34 10 2a <-- 0x2a63 SensorData(Null):[ ]
 CAD: 83.00
23 0 7e 0 0 a5 34 f4 2c <-- 0x2a63 SensorData(Null):[ ]

The Sensordata(Null):[] is new and not desired. 

### Steps to reproduce

1. Turn on ESP-32
2. Connect CPS sensor (i.e. another Smartspin2k)
3. look at debugging output.

**Expected behavior**

When no FTMS device is attached, Sensordata(Null):[] should not be in the debug data.

**Actual behavior**

Sensordata(Null):[] is spammed on each BLE Notify Callback.

**Comment by doudar** [comment]
The best fix would be adding the CPS service to SensorDataFactory 😅

**Comment by kadaan** [comment]
I was hope you would add CPS there at some point ;)

**Comment by doudar** [comment]
I probably can if you'd like me to work on it. 

I've read your code enough that I mostly understand what's going on and should be able to add in CPS. 

Besides that, it would be good for me. 

Let me know.

**Comment by doudar** [comment]
This has been addressed in the upcoming release. Will close once testing is complete.

**Comment by doudar** [comment]
Fixed within #134
