### ISSUE TITLE
[FR] Server characteristic faildown 

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#129]
**Describe the solution you'd like**
There should be a faildown method for determining which services and or characteristics we want to subscribe to from a remote BLE server. I.e.

Is there FTMS Service? - Yes then Connect to that. 
No VV
Is there Cycling Power Service? - Yes, then Connect to that. 
No VV
Is There Cycling Speed and Cadence Service?? Yes, then connect to that. 

Currently, we're just taking the luck of the draw and **Assume** that the first advertised charUUID is the best one the device broadcasts. 

[![Assume Video](Pictures/youtube.png)(https://youtu.be/LfvTwv5o1Qs)
https://www.youtube.com/watch?v=LfvTwv5o1Qs

**Comment by kadaan** [comment]
This shouldn’t be hard to implement, but it will only have an effect if explicit pairing has not been selected.

**Comment by doudar** [comment]
Adding more thoughts, 

My bike trainer separate FTMS, CPS and CSC services. It would be nice to be able to choose exactly what services I want but then use the faildown logic if "any" (or any's future likeness) is selected.
