### ISSUE TITLE
Create wider variety of knob inserts

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#14]
The current inserts probably only work on select models of Schwinn spin bikes. Inserts need to be created which work with more models and the models they work with should be noted in the description or a data table setup. 

A lot of newer Chinese spin bikes are coming out with round textured knobs.  Inserts printed with flexible TPU would probably work well for these. TPU is probably a great material in general for inserts but I haven't tried it yet.

**Comment by doudar** [comment]
HMC inserts created

**Comment by doudar** [comment]
May consider making the "knob cup" larger so that more inserts are actually inserted into the cup instead of the current issue with the HMC adapter which ends up being larger than the knob cup. This will result in less material overall being needed for printing/manufacture.

**Comment by doudar** [comment]
Revmaster-Spin_Adaptor added to inserts

**Comment by fireyeti** [comment]
@ doudar , looks good to me on tinkercad! 

You mean you don't just rip out the dremel?!

**Comment by doudar** [comment]
Slowly building a nice library
