### ISSUE TITLE
Not recognised in Zwift

### ISSUE THREAD

**Issue by paul999666** [doudar/SmartSpin2k#255]
### Steps to reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior**

**Actual behavior**

### Additional Information
* If you provide debug output and it is long, consider using [Pastebin](https://pastebin.com/) and paste a link in this issue to keep the issue easier to read. 
* Provide pictures or links to videos that clearly demonstrate the issue.

**Comment by paul999666** [comment]
Hi made up the smartspin2k , every thing seems to work ok except I can't connect to device on bluetooth for connecting to Zwift, don't know if it is a issue or something i'm not doing correctly, any help would be appreciated

**Comment by MarkusSchneider** [comment]
Had the same Problem. First check if your Bluetooth Device supports the right Standard.
For Windows you can follow this guide: https://support.microsoft.com/en-us/windows/what-bluetooth-version-is-on-my-pc-f5d4cff7-c00d-337b-a642-d2d23b082793.
Version 5.0 should work.
If this is not working, try to connect via Zwift Companion App with your mobile.
Sometimes SmartSpin is not found in the ERG-Device section.
What worked for me is to select SmartSpin as Heart rate Device. Then connect the ERG-Device and remove the Heart-rate Device.

**Comment by paul999666** [comment]
yeah tried that,using bluetooth 5  On the PC the device is not discoverable and through the mobile although I can pair with the smartspin I can't add anything to zwift as it is not seeing anything, not sure if its my bluetooth or the smartspin

**Comment by MarkusSchneider** [comment]
SmartSpin2k uses BLE. So don't pair with your Laptop. Let Zwift discover it. If you have already paired it. Reboot and try again. 
What worked for me was to use the Companion App:
https://support.zwift.com/en_us/using-the-zwift-companion-app-Hybn8qzPr

**Comment by paul999666** [comment]
Thanks for the info all working now cheers 👍
