### ISSUE TITLE
[FR] Simple speed tracking through reed switches

### ISSUE THREAD

**Issue by pupdeg** [doudar/SmartSpin2k#271]
Many exercise bikes have a reed switch or other magnetic sensor inside them to detect flywheel cycles for output to an onboard computer, and for ones that don't, you could easily add one mounted to either the pedals or the flywheel. This general measure of cadence could be detected through a couple of pins on the ESP32 board, and could be used for speed calculations using a lookup chart based on the resistance setting, or just for cadence data. 

While heart rate works well for power, instant cadence data could provide better accuracy and reduce latency.

**Comment by doudar** [comment]
It would/should be easy to implement if anyone wants to have at it. 

For the pcb, we’d need to break out some pins as well.
