### ISSUE TITLE
[FR] RGT HR Support 

### ISSUE THREAD

**Issue by pupdeg** [doudar/SmartSpin2k#273]
Is RGT Cycling fully supported? I'm just using the program for the virtual power meter (works great in Zwift for me), but in RGT Cycling the SS2K device doesn't seem to pass through the heart rate information. It's not a huge deal, it passes through the derived power no problem, but it'd be useful if it showed heart rate too.

**Comment by doudar** [comment]
We worked on this a bunch last year and both RGT and Fulgaz seemingly will not accept Heart Rate service from a device that has cycling power service, cycling speed and cadence service or Fitness Machine Service. 

I think we’d need to be able to present a second (fake) BLE device with only the Heart Rate Service, but it’s currently not possible with the ESP32.

**Comment by doudar** [comment]
@h2zero , do you think there’s any way to create a second NIMBLE_DEVICE on the same esp32? 

The issue we have is a certain Clients that will not accept the Heart Rate Service when it’s combined with other services (see above) - it could be worked around if we could (spoof) another Device.

**Comment by h2zero** [comment]
That wouldn't really be possible. What you can do though is dynamically change the services of the server. What is the client rejecting? I mean does it just disconnect if the server has other services? Or is it refusing to connect if the advertisement doesn't match something?

**Comment by doudar** [comment]
It’s refusing to connect if it’s connected to one of the other services (from what I remember)

**Comment by EdKingscote** [comment]
I disabled device filtering in Fulgaz and the HRM showed up on the SS2K to connect and gave me data that looked reasonable.
