### ISSUE TITLE
[BUG] Debugging not working in iOS

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#327]
### Description

Debugging isn't working in AP mode with an iOS device. It works fine in STA mode.

### Steps to reproduce

1. Connect iPhone or iPad to SmartSpin2K Wifi.
2. Go to SS2K Website.
3. Navigate to status page.
4. Debugging window shows loading. 

**Expected behavior**

Debugging information should show up.

**Actual behavior**

No Debugging Information.

### Additional Information
* This only happens using the SS2K in AP mode. In STA mode, debugging with websockets works normally.
![image](https://user-images.githubusercontent.com/17362216/155239313-c014bef4-61de-4e5f-8639-286e374cd6ea.png)

**Comment by doudar** [comment]
Nevermind.... I blame old .html files.

**Comment by doudar** [comment]
No clue where to start on this one Markus...

This time it's the same in both the automatic login page as well as opening directly in the browser.

**Comment by MarkusSchneider** [comment]
mmh... only way that I know to figure out what happens is to debug IPhone / IPad Safari Browser. 
https://appletoolbox.com/use-web-inspector-debug-mobile-safari/

But you need a Mac computer to get it running.

Other way to get some information is to intercept console.log (monkey patch or write your own console.log) and send logs via http / ajax to a web server. Web Server can then write logs to server log. 

Or you can try Browser Stack https://www.browserstack.com/guide/debug-iphone-safari-on-windows
but I never used it. Don't know if it works.

Let my know if I can help but unfortunately I don't have an apple device to test  😒.

**Comment by doudar** [comment]
I'll see if I can get anything for you. Might take a while as I've got a busy week coming up. It's lower priority anyway.

**Comment by MarkusSchneider** [comment]
Other idea, 
lets write the console log into a <div> at the status page.
When I have time this week, I'll try to get it running.

**Comment by MarkusSchneider** [comment]
Hi Anthony,

I've added a function to status.html to print all errors into the debug info.
https://github.com/doudar/SmartSpin2k/blob/a03e1717a055c3a3e1ef1e302e64bacb4ad9d9d4/data/status.html#L262-L275

![image](https://user-images.githubusercontent.com/7011066/155374865-77e157b2-b850-4135-ba25-cccbb3f683d7.png)

Hope this help to find out why you can not see the log messages in AP Mode.

**Comment by doudar** [comment]
> Hi Anthony,
> 
> 
> 
> I've added a function to status.html to print all errors into the debug info and added some debug messages.
> 
> 
> 
> https://github.com/doudar/SmartSpin2k/blob/a03e1717a055c3a3e1ef1e302e64bacb4ad9d9d4/data/status.html#L262-L275
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/7011066/155374865-77e157b2-b850-4135-ba25-cccbb3f683d7.png)
> 
> 
> 
> Hope this help to find out why you can not see the log messages in AP Mode.
> 
> 

Wow, cool that's a great idea!

**Comment by doudar** [comment]
Sorry this too a while Markus. Swamped here.

Unfortunately this is all I'm getting:

![image](https://user-images.githubusercontent.com/17362216/156799493-97d797ff-58fb-4eec-a7ec-65fbc04a83df.png)

**Comment by doudar** [comment]
Fixed...Hmmm Why didn't I close this earlier
