### ISSUE TITLE
[FR] Direct mount for Bowflex C7

### ISSUE THREAD

**Issue by eMadman** [doudar/SmartSpin2k#389]
I have a first draft in @alexquilty and a user's hands.  Per feedback form @doudar , a few minor changes are needed before I commit and merge my changes

- A slot in the top/bottom of the yoke to allow some compression to bite onto the sliding arm
- because the bike mount is intended to be a part of the whole unit on this bike, we need easier access to the velcro strap to ease mounting/dismounting
- Consider removing the need for foam tape on the yoke.  Fewer points of articulation introduce a risk of breakage if the e-stop is smashed.  The foam tape prevents sliding

I can test fitment on the 3cm seat tube on my C6

**Comment by doudar** [comment]
@eMadman , can this be closed?

**Comment by eMadman** [comment]
Fixed in #401
