### ISSUE TITLE
[BUG] Setting BT source to "none" is resetting to Any

### ISSUE THREAD

**Issue by eMadman** [doudar/SmartSpin2k#413]
### Description
This is affecting a user trying to work with QZ.

The "None" setting on the bluetooth settings page is not sticking - it's going into the "device not found" routine

### Steps to reproduce

1. Set Power Meter or HRM (or both) to none on the Bluetooth Settings Screen
2. Save changes

**Expected behavior**
SS2K stops seeking BLE connection

**Actual behavior**
SS2K reboots and initiates bluetooth scan, connecting to nearby devices

**Comment by doudar** [comment]
I'll check into it. Is this only on the newest firmware? Is there a log? Is it saving the "none" setting and still scanning or does it say "any" in the selected devices?

Edit:
I was able to reproduce it. no further info needed.

**Comment by rp8082** [comment]
I’m the guy that is having the issue. I am able to change the HRM from any to none. But I can’t change power meter from any to none. After pressing “Save Changes”, the software says “setting saved” but the stalls out when refreshing page. It hangs there until I exit out of that screen. I don’t know how to capture a logging file for you b

**Comment by rp8082** [comment]
Doudar Great, I just saw your update to Emad. Thanks!

**Comment by doudar** [comment]
> I’m the guy that is having the issue. I am able to change the HRM from any to none. But I can’t change power meter from any to none. After pressing “Save Changes”, the software says “setting saved” but the stalls out when refreshing page. It hangs there until I exit out of that screen. I don’t know how to capture a logging file for you b

No problem - I was able to reproduce it. Thanks for the report! 

This should be an easy fix.

**Comment by doudar** [comment]
Fixed by #414 
[firmware.zip](https://github.com/doudar/SmartSpin2k/files/10247392/firmware.zip)

Here's a testing binary. Unzip - make sure the name is exactly firmware.bin and upload via the web interface admin/admin

**Comment by eMadman** [comment]
Confirmed on bench test

**Comment by rp8082** [comment]
Hello Anthony. Just uploaded the new firmware. Works perfectly.  Also, QZ app is not controlling it all and is taking resistance values from Fulgaz and changing resistance per the grade changes. Thank you for the rapid patch on the firmware!!!
