### ISSUE TITLE
Display Software Version on Status Page

### ISSUE THREAD

**Issue by fireyeti** [doudar/SmartSpin2k#43]
Display software version number on status page.
Example attached
![Version](https://user-images.githubusercontent.com/76080977/102926837-b986c380-4463-11eb-8b44-ec37b2485b60.png)

**Comment by doudar** [comment]
Good idea :)

**Comment by doudar** [comment]
Complete!

**Comment by doudar** [comment]
not exact but I got pretty close:
![image](https://user-images.githubusercontent.com/17362216/102940467-04113b80-4476-11eb-8ce0-f9e7e8abfaa4.png)

**Comment by fireyeti** [comment]
Very nice!
