### ISSUE TITLE
PCB v2 capacitor values do not match.

### ISSUE THREAD

**Issue by serbasan** [doudar/SmartSpin2k#508]
### Description

PCB v2 capacitor values do not match.

Could you clarify this for me. I have purchased the v2 PCB but the values on the board do not match those in the documentation.

Thank you.

![pcb_assembly jpg](https://github.com/doudar/SmartSpin2k/assets/21089192/95e0a2c9-3de9-47ec-9b84-f64c29c256dc)
![photo_2023-12-19 23 10 12](https://github.com/doudar/SmartSpin2k/assets/21089192/c66b1754-b493-4206-9181-c55050181e78)
<img width="954" alt="Captura de pantalla 2023-12-19 a las 23 07 07" src="https://github.com/doudar/SmartSpin2k/assets/21089192/404d5d30-5193-4ab0-8382-978fe9ae9416">

**Comment by doudar** [comment]
Their values are not terribly important, as long as you have one very small ~.1uf and one large (10-100uf) capacitor. Just make sure the polarity is correct if using an electrolytic capacitor.
