### ISSUE TITLE
wifi password SmartSpin2kFirmware-24.2.27.bin

### ISSUE THREAD

**Issue by Bofunga79** [doudar/SmartSpin2k#536]
I downgraded to SmartSpin2kFirmware-24.2.27.bin, now it asks for a password for the SSID "SmartSpin2k" -> "password" does not work?

**Comment by doudar** [comment]
Fixed before the bug report 😅

Hopefully I stay this lucky.

If you need a new binary (other than the one in the app), there will be an auto build soon.
