### ISSUE TITLE
ESP32 test, Powertap P1 : Zwift sees 100W only

### ISSUE THREAD

**Issue by sspieser** [doudar/SmartSpin2k#66]
Hello,
Just took 5 minutes to play with the ESP32... Paired to WIFI, paired to my Powertap P1 (seen Powertap P1.R, saved). Then Zwift sees the Smartspin2K : but power is 100 W ! 
I assume the ESP32 is not seeing the power from the powertap, or the ESP32 is not really associated, or... and in that case values are broadcasted?

Note:  I did not paired HR ; but HR is of no use for the smart trainer right ? And it's ANT+ anyway....

Thx, rgds, Seb

**Comment by doudar** [comment]
I see you closed the issue. Were you able to get it working?

If not, try a scan/reconnect again to solve the power issue.

In the green debugging window, you should see something like CAD 90 (or some other number) if your powermeter is connected correctly. 

You are correct. HR doesn't need to be connected, only for HR->PWR calculation if you don't have a power meter.
