### ISSUE TITLE
Compatibility wiki page

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#68]
We need a page on the wiki that shows critical measurements (I.e. back of head tube to center of knob) and how to take them (with examples). 

😀

**Comment by fireyeti** [comment]
I’m on it. Great idea!

**Comment by doudar** [comment]
According to my measurements on Fusion 360, the minimum distance from knob center to back of head tube is 60mm

**Comment by doudar** [comment]
Center of knob to "front" is 54mm. Could mount backwards, but I'm not really keen on it as sweat might run back and down to the connectors.

**Comment by doudar** [comment]
Center of knob to either side is 33mm

**Comment by fireyeti** [comment]
Completed draft one. Will add photos with SS2k measurements installed to show clearance requriements.

**Comment by doudar** [comment]
Well done @fireyeti
