### ISSUE TITLE
Create Parts List

### ISSUE THREAD

**Issue by doudar** [doudar/SmartSpin2k#7]

**Comment by ciferkey** [comment]
The [DIY Building Instructions Page](https://www.smartspin2k.com/diy-building-instructions) says the following under the parts list:

> Refer to the wiki for questions about where to obtain parts. 

I haven't actually been able to locate anything that actually contains the information. Was it moved / lost in a refactor?

**Comment by eMadman** [comment]
> The [DIY Building Instructions Page](https://www.smartspin2k.com/diy-building-instructions) says the following under the parts list:
> 
> > Refer to the wiki for questions about where to obtain parts.
> 
> I haven't actually been able to locate anything that actually contains the information. Was it moved / lost in a refactor?

Good catch.  There's a more up-to-date docs site with this information.  There's assembly and sourcing info here: https://docs.smartspin2k.com/documentation/assembly.html .  The Github wiki was getting cumbersome with embedded media.  

I've added the link to the google doc.
