### ISSUE TITLE
Knob cover for BH-SB3 spinbike issue

### ISSUE THREAD

**Issue by sspieser** [doudar/SmartSpin2k#72]
Hello,
The printed part for the SB3 knob does not fit ; here are some pictures : 
[https://photos.app.goo.gl/GM4VxLWre1n7vYzr9](https://photos.app.goo.gl/GM4VxLWre1n7vYzr9)
[https://photos.app.goo.gl/t7VuRxsENP42sbmN9](https://photos.app.goo.gl/GM4VxLWre1n7vYzr9)
[https://photos.app.goo.gl/yYytiPBgKsXemeVh9](https://photos.app.goo.gl/GM4VxLWre1n7vYzr9)

Do you think, you could change a bit the design, maybe some milimeters wider (inner) and 1 or 2 cm higher?

Thanks for your help!

**Comment by doudar** [comment]
Sure - 3 mm wider and 20mm taller? I can do it later this evening.

**Comment by sspieser** [comment]
Thanks : 4mm more in the whole diameter I guess, and in that case 10mm
taller (deeper I mean...) should be enough.

Another question : I miss the mounting part, which one do you advice,
Mounting_StrapV2.STL
<https://github.com/doudar/SmartSpin2k/blob/master/Hardware/Mounting_StrapV2.STL>
or
the HeadTubeStrap.stl
<https://github.com/doudar/SmartSpin2k/blob/master/Hardware/HeadTubeStrap.stl>
 ?

Oh, and of course there is no hurry at all :-)

Thx,
S


Le dim. 24 janv. 2021 à 21:38, Anthony Doud <notifications@github.com> a
écrit :

**Comment by doudar** [comment]
Use strap V2. You might need to sand the barbs on it a very little bit so it fits perfectly.

I'll adjust the knob tonight.

**Comment by doudar** [comment]
The new file is uploaded. Check out https://github.com/doudar/SmartSpin2k/blob/master/Hardware/Inserts/Inserts%20for%20V1%20Cup/BH%20SB3%20spinbike%20Insert%20v3.stl

**Comment by doudar** [comment]
I should add that it's pretty easy to mod this one if you need. The .f3d file is:
https://github.com/doudar/SmartSpin2k/blob/master/Hardware/Inserts/Inserts%20for%20V1%20Cup/BH%20SB3%20spinbike%20%2BInsert%20v3.f3d

**Comment by sspieser** [comment]
OK thanks, I'll have it printed again...
Which software do you use to edit that kind of file ?

Le lun. 25 janv. 2021 à 18:59, Anthony Doud <notifications@github.com> a
écrit :

**Comment by doudar** [comment]
Fusion 360 on those parts. It's free for hobbyists. 

https://www.autodesk.com/products/fusion-360/personal

**Comment by sspieser** [comment]
Hello !
I have just received the new part, and it will work fine I guess,, thank
you !
Next step : the electronic part...

Good WE,
S


Le lun. 25 janv. 2021 à 19:24, Anthony Doud <notifications@github.com> a
écrit :

**Comment by doudar** [comment]
Great to hear!

Good luck!

**Comment by sspieser** [comment]
Sorry, first question : what kind of wires should I use ? I only have very
tight wires from NodeMCU / I2C breadboard, and that may not be enough for a
stepper...

Thx,

Le lun. 1 févr. 2021 à 16:42, Anthony Doud <notifications@github.com> a
écrit :

**Comment by doudar** [comment]
I'm guessing you mean small wires?  It doesn't take much. I think I'm using 22ga? Whatever regular RC servo wires are.

**Comment by sspieser** [comment]
Thanks, I have found 24awg 🙂

Le sam. 6 févr. 2021 à 16:02, Anthony Doud <notifications@github.com> a
écrit :
