### ISSUE TITLE
After submitting settings, return to settings page

### ISSUE THREAD

**Issue by kadaan** [doudar/SmartSpin2k#97]
After submitting settings changes, the result page should notify of success and then return to the settings page.

**Comment by doudar** [comment]
I've been thinking about this also. 

I'd like to keep the server.on() for this unified across multiple pages for simplicity so the redirect would either need to be handled via Javascript or maybe the post data could contain which page the information was posted from for the server redirect. 

The relevant server.on() is at:
https://github.com/doudar/SmartSpin2k/blob/663605769f40d7881cd8154dd3dd030436b49af6/src/HTTP_Server_Basic.cpp#L143
